language: en
commands:
  cmd1:
    name: the overworld
    command: overworld
    permission: none
    world: world
    x: 0.0
    y: 80.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0
  cmd2:
    name: the nether
    command: nether
    permission: none
    world: world_nether
    x: 0.0
    y: 80.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0
  cmd3:
    name: the end
    command: end
    permission: none
    world: world_the_end
    x: 0.0
    y: 80.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0